CREATE TABLE LOCAL_PR(
ID_LOCAL NUMBER(5) NOT NULL,
RENTA NUMBER(7,2) NOT NULL
);

CREATE  TABLE EMPLEADO(
ID_EMPLEADO NUMBER(5),
NOMPILA VARCHAR(20) NOT NULL,
APELLIDOPATER VARCHAR(20) NOT NULL,
APELLIDOMATER VARCHAR(20) 
);

CREATE TABLE TECNICO(
ID_TECNICO NUMBER(5),
ID_EMPLEADO NUMBER(5) NOT NULL UNIQUE 
);

CREATE TABLE TELEF_TECNICO(
TELEFONO NUMBER(10),
ID_TECNICO NUMBER(5)
);

CREATE TABLE ENCARGADO(
ID_ENCARGADO NUMBER(5),
ID_EMPLEADO NUMBER(5)NOT NULL UNIQUE,
CORREO VARCHAR(50) NOT NULL UNIQUE ,
ID_LOCAL NUMBER(5) NOT NULL
);


CREATE TABLE TELEF_ENCARGADO(
TELEFONO NUMBER(10) , 
ID_ENCARGADO NUMBER(5)
);

CREATE TABLE CREAN(
ID_CREAN NUMBER(5),
ID_LOCAL NUMBER(5) NOT NULL,
ID_TORNEO NUMBER(5) NOT NULL,
FECHA_TORNEO DATE NOT NULL
);



CREATE TABLE TORNEO(
ID_TORNEO NUMBER(5),
JUEGO VARCHAR(20) NOT NULL
);


CREATE TABLE TIPO(
ID_TIPO NUMBER(2),
DESCPREFERENTE VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE CLIENTE (
NUM_CLIENTE NUMBER(5),
NOMPILA VARCHAR (20) NOT NULL,
APELLIDOPATER VARCHAR(20) NOT NULL,
APELLIDOMATER VARCHAR(20),
ID_TIPO NUMBER(5) NOT NULL
);


CREATE TABLE CORREOCLIENTE(
NUM_CLIENTE NUMBER(5),
CORREO VARCHAR(50)
);

CREATE TABLE PREFETORNEO(
PREFTORN NUMBER(5),
NUM_CLIENTE NUMBER(5) NOT NULL,
NO_INSCRIPCION NUMBER (5) NOT NULL,
ID_EQUIPO_TORN NUMBER(3)NOT NULL ,
ID_TORNEO NUMBER(5) NOT NULL
);

CREATE TABLE EQUIPOTORNEO(
ID_EQUIPO_TORN NUMBER(5),
NOMBRE_EQUIPO VARCHAR(20) NOT NULL UNIQUE
);



CREATE TABLE CONSOLA(
ID_EQUIPO NUMBER(10),
ID_MARCA NUMBER(3) NOT NULL,
ID_CAPACIDAD NUMBER(3)NOT NULL,
ID_MODELO NUMBER(3) NOT NULL,
NUM_SERIE VARCHAR(20) NOT NULL UNIQUE,
ID_LOCAL NUMBER(5) NOT NULL 
);

CREATE TABLE RENTACLIENTE(
ID_RENTA NUMBER(10),
ID_EQUIPO NUMBER(10) NOT NULL,
NUM_CLIENTE NUMBER(10) NOT NULL,
ID_VIDEOJUEGO NUMBER(5) NOT NULL,
NO_EJEMPLAR NUMBER(5)NOT NULL,
TIEMPO_RENTA DATE NOT NULL
);

CREATE TABLE MARCA(
ID_MARCA NUMBER(3),
MARCA VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE CAPACIDAD(
ID_CAPACIDAD NUMBER(3),
CAPACIDAD VARCHAR(20) NOT NULL UNIQUE
);
CREATE TABLE MODELO(
ID_MODELO NUMBER(3),
MODELO VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE REPARACONSOLA(
ID_REPARA NUMBER(5),
ID_TECNICO NUMBER(5) NOT NULL,
ID_EQUIPO NUMBER(10) NOT NULL,
FECHA_REPORTE DATE NOT NULL,
FECHA_REPARACION DATE NOT NULL,
REPORTE_ESTADO VARCHAR(20) NOT NULL,
DESC_FALLA VARCHAR(100) NOT NULL
);

CREATE TABLE EJEMPLAR(
ID_VIDEOJUEGO NUMBER(5),
NO_EJEMPLAR NUMBER(5) NOT NULL,
ID_ESTADO NUMBER(1)NOT NULL,
ID_MODELO NUMBER(20)NOT NULL,
ID_EQUIPO NUMBER(5) NOT NULL 
);

CREATE TABLE ESTADO(
ID_ESTADO NUMBER(1),
ESTADO VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE VIDEOJUEGO(
ID_VIDEOJUEGO NUMBER(5),
NOMBRE VARCHAR (50) NOT NULL UNIQUE,
ID_DESC NUMBER(5) NOT NULL,
FECHA_LANZAMIENTO DATE NOT NULL,
ID_CLAS NUMBER(5) NOT NULL,
PLATAFORMA NUMBER(3) NOT NULL,
COSTO NUMBER(5) NOT NULL
);

CREATE TABLE DESCRIPCION(
ID_DESC NUMBER(5),
DESCRIPCION VARCHAR (50) NOT NULL UNIQUE
);
CREATE TABLE CLASIFICACION(
ID_CLAS NUMBER(5),
CLASIFICACION VARCHAR (50) NOT NULL UNIQUE
);




DROP TABLE CLIENTE  CASCADE CONSTRAINTS;
DROP TABLE CONSOLA  CASCADE CONSTRAINTS;
DROP TABLE CORREOCLIENTE  CASCADE CONSTRAINTS;
DROP TABLE CREAN  CASCADE CONSTRAINTS;
DROP TABLE EJEMPLAR  CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO  CASCADE CONSTRAINTS;
DROP TABLE ENCARGADO  CASCADE CONSTRAINTS;
DROP TABLE LOCAL_PR  CASCADE CONSTRAINTS;
DROP TABLE PREFETORNEO  CASCADE CONSTRAINTS;
DROP TABLE REPARACONSOLA  CASCADE CONSTRAINTS;
DROP TABLE TECNICO  CASCADE CONSTRAINTS;
DROP TABLE TELEF_ENCARGADO  CASCADE CONSTRAINTS;
DROP TABLE TELEF_TECNICO  CASCADE CONSTRAINTS;
DROP TABLE TIPO  CASCADE CONSTRAINTS;
DROP TABLE TORNEO  CASCADE CONSTRAINTS;
DROP TABLE VIDEOJUEGO  CASCADE CONSTRAINTS;
DROP TABLE EQUIPOTORNEO  CASCADE CONSTRAINTS;
DROP TABLE MARCA  CASCADE CONSTRAINTS;
DROP TABLE CAPACIDAD  CASCADE CONSTRAINTS;
DROP TABLE MODELO  CASCADE CONSTRAINTS;
DROP TABLE ESTADO  CASCADE CONSTRAINTS;
DROP TABLE DESCRIPCION  CASCADE CONSTRAINTS;
DROP TABLE CLASIFICACION  CASCADE CONSTRAINTS;
DROP TABLE RENTACLIENTE CASCADE CONSTRAINTS;

COMMIT;

CLEAR SCREEN;


