
--local
ALTER TABLE LOCAL_PR ADD CONSTRAINT PK_LOCAL PRIMARY KEY (ID_LOCAL);
--Empleado
ALTER TABLE Empleado ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO);
--Tecnico
ALTER TABLE TECNICO ADD CONSTRAINT PK_TECNICO PRIMARY KEY (ID_TECNICO);
ALTER TABLE TECNICO ADD CONSTRAINT FK_EMPLEADOTEC FOREIGN KEY (ID_EMPLEADO)
REFERENCES EMPLEADO (ID_EMPLEADO);
--Telefono del Tecnico
ALTER TABLE TELEF_TECNICO ADD CONSTRAINT PK_TELEFTEC PRIMARY KEY (ID_TECNICO,TELEFONO);
ALTER TABLE TELEF_TECNICO ADD CONSTRAINT FK_TECNICOTEL FOREIGN KEY (ID_TECNICO)
REFERENCES TECNICO(ID_TECNICO);
--ENCARGADO
ALTER TABLE ENCARGADO ADD CONSTRAINT PK_ENCARGADO PRIMARY KEY (ID_ENCARGADO);
ALTER TABLE ENCARGADO ADD CONSTRAINT FK_EMPLEADOENC FOREIGN KEY (ID_EMPLEADO)
REFERENCES EMPLEADO (ID_EMPLEADO);
ALTER TABLE ENCARGADO ADD CONSTRAINT FK_LOCALENC FOREIGN KEY (ID_LOCAL)
REFERENCES LOCAL_PR (ID_LOCAL);

--TELEFONO ENCARGADO
ALTER TABLE TELEF_ENCARGADO ADD CONSTRAINT PK_TELEFENCAR PRIMARY KEY (ID_ENCARGADO, TELEFONO);
ALTER TABLE TELEF_ENCARGADO ADD CONSTRAINT FK_ENCARGADOTEL FOREIGN KEY (ID_ENCARGADO)
REFERENCES ENCARGADO(ID_ENCARGADO);

--TORNEO
ALTER TABLE TORNEO ADD CONSTRAINT PK_TORNEO PRIMARY KEY (ID_TORNEO);

--CREAN
ALTER TABLE CREAN ADD CONSTRAINT PK_CREAN PRIMARY KEY (ID_CREAN);
ALTER TABLE CREAN ADD CONSTRAINT FK_LOCALCREAN FOREIGN KEY (ID_LOCAL)
REFERENCES LOCAL_PR (ID_LOCAL);
ALTER TABLE CREAN ADD CONSTRAINT FK_CREANTORNEO FOREIGN KEY (ID_TORNEO)
REFERENCES TORNEO (ID_TORNEO);




--TIPO DE CLIENTE
ALTER TABLE TIPO ADD CONSTRAINT PK_TIPO PRIMARY KEY (ID_TIPO);

--CLIENTE

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (NUM_CLIENTE);
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTETIPO FOREIGN KEY (ID_TIPO)
REFERENCES TIPO (ID_TIPO);

--CORREO CLIENTE
ALTER TABLE CORREOCLIENTE ADD CONSTRAINT PK_CORREOCLIENTE PRIMARY KEY (CORREO,NUM_CLIENTE);
ALTER TABLE CORREOCLIENTE ADD CONSTRAINT FK_CORREOCLIENTE FOREIGN KEY (NUM_CLIENTE)
REFERENCES CLIENTE(NUM_CLIENTE);

--EQUIPOS
ALTER TABLE EQUIPOTORNEO  ADD CONSTRAINT PK_EQUIPOCOMP PRIMARY KEY (ID_EQUIPO_TORN);

--PREFTORNEO
ALTER TABLE PREFETORNEO  ADD CONSTRAINT PK_PREFTORNEO PRIMARY KEY (PREFTORN);
ALTER TABLE PREFETORNEO  ADD CONSTRAINT FK_PREFTORNEOCLIENTE FOREIGN KEY (NUM_CLIENTE)
REFERENCES CLIENTE (NUM_CLIENTE);
ALTER TABLE PREFETORNEO  ADD CONSTRAINT FK_PREFTORNEOTORN FOREIGN KEY (ID_TORNEO)
REFERENCES TORNEO (ID_TORNEO);
ALTER TABLE PREFETORNEO  ADD CONSTRAINT FK_EQUIPOTORN FOREIGN KEY (ID_EQUIPO_TORN)
REFERENCES EQUIPOTORNEO (ID_EQUIPO_TORN);



--MARCA
ALTER TABLE MARCA  ADD CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA);

--CAPACIDAD
ALTER TABLE CAPACIDAD  ADD CONSTRAINT PK_CAPACIDAD PRIMARY KEY (ID_CAPACIDAD);

--MODELO
ALTER TABLE MODELO  ADD CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO);

--CONSOLSA

ALTER TABLE CONSOLA  ADD CONSTRAINT PK_CONSOLA PRIMARY KEY (ID_EQUIPO);
ALTER TABLE CONSOLA  ADD CONSTRAINT FK_CONSOLALOCAL FOREIGN KEY (ID_LOCAL)
REFERENCES LOCAL_PR (ID_LOCAL);
ALTER TABLE CONSOLA  ADD CONSTRAINT FK_CONSOLAMARCA FOREIGN KEY (ID_MARCA)
REFERENCES MARCA (ID_MARCA);
ALTER TABLE CONSOLA  ADD CONSTRAINT FK_CONSOLACAPACIDAD FOREIGN KEY (ID_CAPACIDAD)
REFERENCES CAPACIDAD (ID_CAPACIDAD);
ALTER TABLE CONSOLA  ADD CONSTRAINT FK_MODELO FOREIGN KEY (ID_MODELO)
REFERENCES MODELO (ID_MODELO);




--REPARACONSOLA

ALTER TABLE REPARACONSOLA  ADD CONSTRAINT PK_REPARACONSOLA PRIMARY KEY (ID_REPARA);
ALTER TABLE REPARACONSOLA  ADD CONSTRAINT FK_REPARACONSOLATECNICO FOREIGN KEY (ID_TECNICO)
REFERENCES TECNICO (ID_TECNICO);
ALTER TABLE REPARACONSOLA  ADD CONSTRAINT FK_REPARACONSOLAEQUIPO FOREIGN KEY (ID_EQUIPO)
REFERENCES CONSOLA (ID_EQUIPO);


--ESTADO
ALTER TABLE ESTADO  ADD CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO);



--DESCRIPCION
ALTER TABLE DESCRIPCION  ADD CONSTRAINT PK_DESC PRIMARY KEY (ID_DESC);
--CLASIFICACION
ALTER TABLE CLASIFICACION  ADD CONSTRAINT PK_CLAS PRIMARY KEY (ID_CLAS);

--VIDEOJUEGO
ALTER TABLE VIDEOJUEGO  ADD CONSTRAINT PK_VIDEOJUEGO PRIMARY KEY (ID_VIDEOJUEGO);
ALTER TABLE VIDEOJUEGO  ADD CONSTRAINT FK_VIDEOJUEGODESC FOREIGN KEY (ID_DESC)
REFERENCES DESCRIPCION(ID_DESC);
ALTER TABLE VIDEOJUEGO  ADD CONSTRAINT FK_VIDEOJUEGOCLAS FOREIGN KEY (ID_CLAS)
REFERENCES CLASIFICACION(ID_CLAS);
ALTER TABLE VIDEOJUEGO  ADD CONSTRAINT FK_VIDEOJUEGOPLATAFORMA FOREIGN KEY (PLATAFORMA)
REFERENCES MARCA(ID_MARCA);


--EJEMPLAR

ALTER TABLE EJEMPLAR  ADD CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_VIDEOJUEGO,NO_EJEMPLAR);
ALTER TABLE EJEMPLAR  ADD CONSTRAINT FK_EJEMPLAREQUIPO FOREIGN KEY (ID_EQUIPO)
REFERENCES CONSOLA(ID_EQUIPO);
ALTER TABLE EJEMPLAR  ADD CONSTRAINT FK_EJEMPLARESTADO FOREIGN KEY (ID_ESTADO)
REFERENCES ESTADO(ID_ESTADO);
ALTER TABLE EJEMPLAR  ADD CONSTRAINT FK_EJEMPLARMODELO FOREIGN KEY (ID_MODELO)
REFERENCES MODELO(ID_MODELO);
ALTER TABLE EJEMPLAR  ADD CONSTRAINT FK_EJEMPLAVIDEOJUEGO FOREIGN KEY (ID_VIDEOJUEGO)
REFERENCES VIDEOJUEGO(ID_VIDEOJUEGO);


--TIEMPO RENTA
ALTER TABLE RENTACLIENTE  ADD CONSTRAINT PK_RENTA PRIMARY KEY (ID_RENTA);
ALTER TABLE RENTACLIENTE  ADD CONSTRAINT FK_RENTAEQUIPO FOREIGN KEY (ID_EQUIPO)
REFERENCES CONSOLA(ID_EQUIPO);
ALTER TABLE RENTACLIENTE  ADD CONSTRAINT FK_RENTACLIENTE FOREIGN KEY (NUM_CLIENTE)
REFERENCES CLIENTE(NUM_CLIENTE);
ALTER TABLE RENTACLIENTE  ADD CONSTRAINT FK_RENTAEJEMPLAR FOREIGN KEY (ID_VIDEOJUEGO,NO_EJEMPLAR )
REFERENCES EJEMPLAR(ID_VIDEOJUEGO,NO_EJEMPLAR);



